import io
from typing import List

class Game:
    output: str
    def do_command(self, words: List[str]) -> str: ...
    def t_suspend(self, verb: None, obj: io.BytesIO) -> None: ...
    def start(self) -> None: ...
    @classmethod
    def resume(cls, save: io.BytesIO) -> None: ...
